name: $(BuildDefinitionName)_[$(Date:yyyyMMdd)]

# Controls when the action will run. 
# Trigger is set to 'none' the pipeline which means you need to start manually.
trigger: none

jobs:
  - job: "Demo_Job"

    # The type of agent that the job will run on
    pool:
      vmImage: 'ubuntu-18.04'

    # Container agent's Docker image name
    container: gr00vysky/iac-demo:latest

    # Steps represent a sequence of tasks that will be executed
    steps:

    - bash: ansible-playbook /opt/automation/ansible/main.yml -e "azure_group_name='demo-group' nginx_default_msg=$(nginx_default_msg)"
      displayName: 'run main.yml playbook'
      env:
        ANSIBLE_HOST_KEY_CHECKING: False
        AZURE_CLIENT_ID: $(client_id)
        AZURE_SECRET: $(secret)
        AZURE_SUBSCRIPTION_ID: $(subscription_id)
        AZURE_TENANT: $(tenant)
